export const myProjects = [
  {
    projectTitle: "Admin Dashboard",
    category: "React & MUI",
    imgPath: "./images/React Admin Dashboard.jpg",
    description: "React Admin Dashboard",
    link: "https://react-admin-dashboard-swart-nine.vercel.app/",
    gitHub: "https://github.com/ahmedAiuop/React-Admin-Dashboard",
    gitProfile: "https://github.com/ahmedAiuop",
  },

  {
    projectTitle: "Flower Shop",
    category: "HTML & CSS",
    imgPath: "./images/flower shop.jpg",
    description:
      "A Responsive E-Commerce Flower Shop Website Design using Html & CSS",
    link: "https://ahmedaiuop.github.io/flower-shop/",
    gitHub: "https://github.com/ahmedAiuop/flower-shop",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Web Design",
    category: "Java Script",
    imgPath: "./images/web design.jpg",
    description: "A Responsive Website Design using Html & CSS & Javascript",
    link: "https://ahmedaiuop.github.io/Special-design/",
    gitHub: "https://github.com/ahmedAiuop/Special-design",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "CRUD",
    category: "Java Script",
    imgPath: "./images/crud.jpg",
    description:
      "Product Management System Website Design using Html & CSS & Javascript",
    link: "https://ahmedaiuop.github.io/Product-Management-System/",
    gitHub: "https://github.com/ahmedAiuop/Product-Management-System",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Dashboard",
    category: "HTML & CSS",
    imgPath: "./images/dashbord.jpg",
    description: "A Responsive Dashboard Website Design using Html & CSS",
    link: "https://ahmedaiuop.github.io/responsive-project/",
    gitHub: "https://github.com/ahmedAiuop/responsive-project",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Photo Editor",
    category: "Java Script",
    imgPath: "./images/photo editor.jpg",
    description: "Photo Editor Website Design using Html & CSS & Javascrip",
    link: "https://ahmedaiuop.github.io/Editor-project/",
    gitHub: "https://github.com/ahmedAiuop/Editor-project",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Bootstrap Design",
    category: "HTML & CSS",
    imgPath: "./images/bootstrap.jpg",
    description: "Bootstrap Website Design",
    link: "https://ahmedaiuop.github.io/bootstrap-project/",
    gitHub: "https://github.com/ahmedAiuop/bootstrap-project",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "AI Image Generator",
    category: "Java Script",
    imgPath: "./images/ai-image.jpg",
    description:
      "Artificial intelligence image generation program using Html & CSS & Javascript",
    link: "https://ahmedaiuop.github.io/Artificial-intelligence-image-generation-program/",
    gitHub:
      "https://github.com/ahmedAiuop/Artificial-intelligence-image-generation-program",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Creative hover menu",
    category: "HTML & CSS",
    imgPath: "./images/hover menu.jpg",
    description: "Creative hover menu Website Design using Html & CSS",
    link: "https://ahmedaiuop.github.io/creative-project/",
    gitHub: "https://github.com/ahmedAiuop/creative-project",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Scrolling Website",
    category: "Java Script",
    imgPath: "./images/scrolling website.jpg",
    description: "Make a Scrolling Website using Html & CSS & Javascript",
    link: "https://ahmedaiuop.github.io/Web-project/",
    gitHub: "https://github.com/ahmedAiuop/Web-project",
    gitProfile: "https://github.com/ahmedAiuop",
  },
  {
    projectTitle: "Store Page",
    category: "Java Script",
    imgPath: "./images/store.jpg",
    description: "Landing Page Design using Html & CSS & Javascript",
    link: "https://ahmedaiuop.github.io/landing-page/",
    gitHub: "https://github.com/ahmedAiuop/landing-page",
    gitProfile: "https://github.com/ahmedAiuop",
  },
];
